In [49]:
import pandas as pd
import numpy as np
from google.colab import files

In [98]:
files.upload()

Saving carprices.csv to carprices.csv


{'carprices.csv': b'Car Model,Mileage,Sell Price($),Age(yrs)\nBMW X5,69000,18000,6\nBMW X5,35000,34000,3\nBMW X5,57000,26100,5\nBMW X5,22500,40000,2\nBMW X5,46000,31500,4\nAudi A5,59000,29400,5\nAudi A5,52000,32000,5\nAudi A5,72000,19300,6\nAudi A5,91000,12000,8\nMercedez Benz C class,67000,22000,6\nMercedez Benz C class,83000,20000,7\nMercedez Benz C class,79000,21000,7\nMercedez Benz C class,59000,33000,5\n'}

In [99]:
df = pd.read_csv('carprices.csv')
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [100]:
dummies = pd.get_dummies(df['Car Model'])
dummies

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [101]:
merged = pd.concat([df, dummies],axis='columns')
merged

Car Model  Mileage  ...  BMW X5  Mercedez Benz C class
0                  BMW X5    69000  ...       1                      0
1                  BMW X5    35000  ...       1                      0
2                  BMW X5    57000  ...       1                      0
3                  BMW X5    22500  ...       1                      0
4                  BMW X5    46000  ...       1                      0
5                 Audi A5    59000  ...       0                      0
6                 Audi A5    52000  ...       0                      0
7                 Audi A5    72000  ...       0                      0
8                 Audi A5    91000  ...       0                      0
9   Mercedez Benz C class    67000  ...       0                      1
10  Mercedez Benz C class    83000  ...       0                      1
11  Mercedez Benz C class    79000  ...       0                      1
12  Mercedez Benz C class    59000  ...       0                      1

[13 rows x 7 columns]

In [133]:
final = merged.drop(['Car Model', 'Mercedez Benz C class'], axis='columns')
final

Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [134]:
X = final.drop(['Sell Price($)'], axis='columns')
X

Mileage  Age(yrs)  Audi A5  BMW X5
0     69000         6        0       1
1     35000         3        0       1
2     57000         5        0       1
3     22500         2        0       1
4     46000         4        0       1
5     59000         5        1       0
6     52000         5        1       0
7     72000         6        1       0
8     91000         8        1       0
9     67000         6        0       0
10    83000         7        0       0
11    79000         7        0       0
12    59000         5        0       0

In [135]:
y = final['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [136]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
# LinearRegression().score()

In [137]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [138]:
model.predict(X)

array([18705.2723644 , 35286.78445645, 24479.19112468, 41245.76426391,
       29882.98779056, 28023.6135243 , 30614.46818502, 21879.57266964,
       12182.34562104, 26183.72387884, 18929.31674102, 20409.80511857,
       30477.15426156])

In [139]:
model.score(X,y) # This linear model provides 94% accuracy

0.9417050937281083

In [144]:
model.predict([[45000, 4, 0, 0 ]]) # Mercedes Benz  4 yo 45000mi

array([36991.31721061])

In [145]:
model.predict([[86000, 7, 0, 1]]) # BMX X5  7 yo 86000mi

array([11080.74313219])

## Using sklearn OneHotEncoder

In [149]:
# With different data set below

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [ ]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

In [124]:
X = dfle[['town','area']].values
X

array([[69000,     6],
       [35000,     3],
       [57000,     5],
       [22500,     2],
       [46000,     4],
       [59000,     5],
       [52000,     5],
       [72000,     6],
       [91000,     8],
       [67000,     6],
       [83000,     7],
       [79000,     7],
       [59000,     5]])

In [125]:
y = dfle.price.values
y

array([18000, 34000, 26100, 40000, 31500, 29400, 32000, 19300, 12000,
       22000, 20000, 21000, 33000])

In [126]:
# Now use one hot encoder to create dummy variables for each of the town

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')

In [127]:
X = ct.fit_transform(X)
X

<13x13 sparse matrix of type '<class 'numpy.float64'>'
	with 26 stored elements in Compressed Sparse Row format>

In [128]:
X = X[:,1:]
X

<13x12 sparse matrix of type '<class 'numpy.float64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [129]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.predict([[0,1,3400]]) # 3400 sqr ft home in west windsor

In [95]:
model.predict([[1,0,2800]]) # 2800 sqr ft home in robbinsville

array([590775.63964739])